# Generated by Django — xeolux_cookiekit initial migration

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CookieKitConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "site_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nom du site",
                    ),
                ),
                (
                    "consent_version",
                    models.CharField(
                        default="1.0.0",
                        max_length=50,
                        verbose_name="Version de consentement",
                    ),
                ),
                (
                    "cookie_name",
                    models.CharField(
                        default="xeolux_cookie_consent",
                        max_length=100,
                        verbose_name="Nom du cookie",
                    ),
                ),
                (
                    "cookie_max_age_days",
                    models.PositiveIntegerField(
                        default=180, verbose_name="Durée du cookie (jours)"
                    ),
                ),
                (
                    "cookie_secure",
                    models.BooleanField(default=True, verbose_name="Cookie Secure"),
                ),
                (
                    "cookie_samesite",
                    models.CharField(
                        choices=[
                            ("Lax", "Lax"),
                            ("Strict", "Strict"),
                            ("None", "None"),
                        ],
                        default="Lax",
                        max_length=10,
                        verbose_name="Cookie SameSite",
                    ),
                ),
                (
                    "banner_position",
                    models.CharField(
                        choices=[
                            ("bottom", "Bas de page"),
                            ("top", "Haut de page"),
                            ("bottom-left", "Bas gauche"),
                            ("bottom-right", "Bas droite"),
                        ],
                        default="bottom",
                        max_length=20,
                        verbose_name="Position du bandeau",
                    ),
                ),
                (
                    "banner_layout",
                    models.CharField(
                        choices=[
                            ("banner", "Bandeau"),
                            ("modal", "Modal centré"),
                            ("floating", "Flottant"),
                        ],
                        default="banner",
                        max_length=20,
                        verbose_name="Layout",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#111111", max_length=20, verbose_name="Couleur de fond"
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#ffffff", max_length=20, verbose_name="Couleur du texte"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#ff6b00",
                        max_length=20,
                        verbose_name="Couleur primaire (boutons)",
                    ),
                ),
                (
                    "primary_text_color",
                    models.CharField(
                        default="#ffffff",
                        max_length=20,
                        verbose_name="Texte bouton primaire",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#2b2b2b",
                        max_length=20,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "secondary_text_color",
                    models.CharField(
                        default="#ffffff",
                        max_length=20,
                        verbose_name="Texte bouton secondaire",
                    ),
                ),
                (
                    "border_radius",
                    models.CharField(
                        default="14px", max_length=20, verbose_name="Border radius"
                    ),
                ),
                (
                    "shadow",
                    models.BooleanField(default=True, verbose_name="Ombre portée"),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="system", max_length=100, verbose_name="Police"
                    ),
                ),
                (
                    "z_index",
                    models.PositiveIntegerField(default=9999, verbose_name="Z-Index"),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True, default="", verbose_name="CSS personnalisé"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Gestion des cookies", max_length=255, verbose_name="Titre"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        default="Nous utilisons des cookies pour améliorer votre expérience, mesurer l'audience et personnaliser certains contenus.",
                        verbose_name="Message",
                    ),
                ),
                (
                    "accept_all_label",
                    models.CharField(
                        default="Tout accepter",
                        max_length=100,
                        verbose_name="Bouton Tout accepter",
                    ),
                ),
                (
                    "reject_all_label",
                    models.CharField(
                        default="Tout refuser",
                        max_length=100,
                        verbose_name="Bouton Tout refuser",
                    ),
                ),
                (
                    "customize_label",
                    models.CharField(
                        default="Personnaliser",
                        max_length=100,
                        verbose_name="Bouton Personnaliser",
                    ),
                ),
                (
                    "save_label",
                    models.CharField(
                        default="Enregistrer mes choix",
                        max_length=100,
                        verbose_name="Bouton Enregistrer",
                    ),
                ),
                (
                    "close_label",
                    models.CharField(
                        default="Fermer",
                        max_length=100,
                        verbose_name="Bouton Fermer",
                    ),
                ),
                (
                    "preferences_title",
                    models.CharField(
                        default="Préférences cookies",
                        max_length=255,
                        verbose_name="Titre modal préférences",
                    ),
                ),
                (
                    "google_analytics_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Google Analytics activé"
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Measurement ID (GA4)",
                    ),
                ),
                (
                    "google_tag_manager_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Google Tag Manager activé"
                    ),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Container ID (GTM)",
                    ),
                ),
                (
                    "meta_pixel_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Meta Pixel activé"
                    ),
                ),
                (
                    "meta_pixel_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Pixel ID",
                    ),
                ),
                (
                    "matomo_enabled",
                    models.BooleanField(default=False, verbose_name="Matomo activé"),
                ),
                (
                    "matomo_site_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Matomo Site ID",
                    ),
                ),
                (
                    "matomo_tracker_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Matomo Tracker URL",
                    ),
                ),
                (
                    "plausible_enabled",
                    models.BooleanField(default=False, verbose_name="Plausible activé"),
                ),
                (
                    "plausible_domain",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Plausible Domain",
                    ),
                ),
                (
                    "custom_head_scripts",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Scripts personnalisés <head>",
                    ),
                ),
                (
                    "custom_body_scripts",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Scripts personnalisés <body>",
                    ),
                ),
                (
                    "cachekit_enabled",
                    models.BooleanField(default=True, verbose_name="CacheKit activé"),
                ),
                (
                    "cachekit_sync_cookie_version",
                    models.BooleanField(
                        default=True,
                        verbose_name="Synchroniser version via CacheKit",
                    ),
                ),
                (
                    "cachekit_version_key",
                    models.CharField(
                        default="cookiekit",
                        max_length=100,
                        verbose_name="Clé de version CacheKit",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Mis à jour le"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration CookieKit",
                "verbose_name_plural": "Configuration CookieKit",
            },
        ),
        migrations.CreateModel(
            name="CookieCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        max_length=50,
                        unique=True,
                        verbose_name="Clé (identifiant)",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=100, verbose_name="Label affiché"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="Requis"),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, verbose_name="Activé par défaut"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie de cookies",
                "verbose_name_plural": "Catégories de cookies",
                "ordering": ["order", "key"],
            },
        ),
        migrations.CreateModel(
            name="CookieScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du script"),
                ),
                (
                    "category",
                    models.CharField(
                        default="analytics",
                        max_length=50,
                        verbose_name="Catégorie de consentement requise",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, verbose_name="Actif"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[("head", "<head>"), ("body", "<body>")],
                        default="head",
                        max_length=10,
                        verbose_name="Position d'injection",
                    ),
                ),
                (
                    "script",
                    models.TextField(verbose_name="Code HTML/Script"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Ordre d'exécution"
                    ),
                ),
            ],
            options={
                "verbose_name": "Script personnalisé",
                "verbose_name_plural": "Scripts personnalisés",
                "ordering": ["position", "order", "name"],
            },
        ),
    ]
